#!/bin/bash

git pull origin master

rm -f ./bin/makefoxsrv
cd ./src/makefoxsrv/
dotnet publish -c Release --self-contained true /p:PublishSingleFile=true
#mv bin/Release/net8.0/linux-x64/publish/makefoxbot ~/bot/bin
cd ../../bin
