//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace makefoxsrv.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("makefoxsrv.lang.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я понимаю и согласен.
        /// </summary>
        internal static string Terms_AgreeButton {
            get {
                return ResourceManager.GetString("Terms.AgreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, ознакомьтесь и согласитесь с следующими требованиями, прежде чем продолжить:
        ///
        ///Подтверждение возраста: Вам должно быть не менее 18 лет и вы должны быть признаны совершеннолетним в вашей юрисдикции.
        ///
        ///Рекомендации по персонажам: Мы не рекомендуем изображать человеческих персонажей в контенте для взрослых. Категорически запрещено создавать изображения несовершеннолетних человеческих персонажей в таких контекстах.
        ///
        ///Соблюдение авторских прав: Создание изображений с использованием авторских персо [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terms_Message {
            get {
                return ResourceManager.GetString("Terms.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Я Makefoxbot, рад помочь вам раскрыть свой творческий потенциал с помощью замечательных изображений в стилях фурри, аниме или мультфильмов с помощью ИИ.
        ///
        ///&lt;b&gt;Как начать:&lt;/b&gt; Прежде чем приступить, рекомендую ознакомиться с документацией в разделе /help, чтобы узнать основы. Готовы исследовать? Давайте ознакомимся с основными правилами:
        ///
        ///&lt;b&gt;Правовые аспекты:&lt;/b&gt;
        ///
        ///&lt;b&gt;Подтверждение возраста:&lt;/b&gt; Вам должно быть не менее 18 лет, и вы должны быть признаны совершеннолетним в вашей юрисдикции.
        ///&lt;b&gt;Рек [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
