//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace makefoxsrv.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("makefoxsrv.lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set!.
        /// </summary>
        internal static string Lang_AnswerCallbackMsg {
            get {
                return ResourceManager.GetString("Lang.AnswerCallbackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 I Understand &amp; Agree.
        /// </summary>
        internal static string Terms_AgreeButton {
            get {
                return ResourceManager.GetString("Terms.AgreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have acknolwedged your acceptance of the terms of service.
        ///
        ///Thank you!.
        /// </summary>
        internal static string Terms_AgreeClicked {
            get {
                return ResourceManager.GetString("Terms.AgreeClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Click the button below to acknowledge your understanding and agreement with these terms.&lt;/b&gt;.
        /// </summary>
        internal static string Terms_AgreePrompt {
            get {
                return ResourceManager.GetString("Terms.AgreePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you may continue, you must review and agree to the following terms of service:
        ///
        ///&lt;b&gt;Age Verification:&lt;/b&gt; You must be at least 18 years old and recognized as a legal adult in your jurisdiction.
        ///
        ///&lt;b&gt;Character Guidelines:&lt;/b&gt; We discourage the depiction of realistic human characters that could be mistaken for real people.  It is explicitly forbidden to create images of underage human characters of any sort.
        ///
        ///&lt;b&gt;Copyright Compliance:&lt;/b&gt; Creation of images using copyrighted characters or trademarks [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terms_Message {
            get {
                return ResourceManager.GetString("Terms.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;You have acknowleged your acceptance of these terms.  Thank you!&lt;/b&gt;.
        /// </summary>
        internal static string Terms_UserAgreed {
            get {
                return ResourceManager.GetString("Terms.UserAgreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I’m Makefoxbot, excited to help you unleash your creativity with fantastic furry, anime, or cartoon images through AI.
        ///
        ///&lt;b&gt;Getting Started:&lt;/b&gt; Before diving in, a quick look over the /help documentation will set you up with the basics. Ready to explore? Let&apos;s cover some ground rules:
        ///
        ///&lt;b&gt;Legal Bits:&lt;/b&gt;
        ///
        ///&lt;b&gt;Age Verification:&lt;/b&gt; You must be at least 18 years old and recognized as a legal adult in your jurisdiction.
        ///&lt;b&gt;Character Guidelines:&lt;/b&gt; We discourage depicting human characters in matur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
